# calendar_utils.py
# Creates Google Calendar events for coach meeting slots
# Uses service account — calendar must be shared with service account email
# Timezone: Asia/Kolkata

from googleapiclient.discovery import build
from google.oauth2.service_account import Credentials
from datetime import datetime, date
import pytz
import streamlit as st
import json
import os

TIMEZONE = "Asia/Kolkata"

# ── Get Calendar service ───────────────────────────────────────────────────
def get_calendar_service():
    raw_json = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")
    if raw_json:
        service_account_info = json.loads(raw_json)
    else:
        service_account_info = dict(st.secrets["GOOGLE_SERVICE_ACCOUNT_JSON"])

    scopes = ["https://www.googleapis.com/auth/calendar"]
    creds  = Credentials.from_service_account_info(service_account_info, scopes=scopes)
    return build("calendar", "v3", credentials=creds)

# ── Parse time string to datetime ─────────────────────────────────────────
# Takes "10:00 AM" and today's date, returns full datetime in IST
def _parse_time(time_str: str, today: date) -> datetime:
    tz = pytz.timezone(TIMEZONE)
    dt = datetime.strptime(f"{today} {time_str}", "%Y-%m-%d %I:%M %p")
    return tz.localize(dt)

# ── Create calendar events for today's meetings ────────────────────────────
# Called after plan is generated
# Creates one event per meeting slot in coach's calendar
# Each event has student name, signal severity, and prep reminder
def create_calendar_events(plan: dict, today: date) -> list:
    """
    Takes generated plan and creates Google Calendar events for meeting slots only
    Returns list of created event links
    """
    try:
        service     = get_calendar_service()
        calendar_id = os.getenv("GOOGLE_CALENDAR_ID") or st.secrets.get("GOOGLE_CALENDAR_ID")
        created     = []

        schedule = plan.get("schedule", [])

        # Meeting time slots — fixed
        meeting_times = {
            "10:00 AM - 11:00 AM": ("10:00 AM", "11:00 AM"),
            "12:00 PM - 1:00 PM":  ("12:00 PM", "1:00 PM"),
            "4:00 PM - 5:00 PM":   ("4:00 PM",  "5:00 PM"),
        }

        for slot in schedule:
            activity = slot.get("activity", "")
            time_key = slot.get("time", "")
            detail   = slot.get("detail", "")

            # Only create events for meeting slots
            if "Meeting" not in activity:
                continue

            if time_key not in meeting_times:
                continue

            start_str, end_str = meeting_times[time_key]
            start_dt = _parse_time(start_str, today)
            end_dt   = _parse_time(end_str,   today)

            # Extract student name from activity like "Meeting — Arjun Kumar"
            student_name = activity.replace("Meeting —", "").replace("Meeting -", "").strip()

            event = {
                "summary": f"Student Meeting — {student_name}",
                "description": f"{detail}\n\nGenerated by Success Coach AI",
                "start": {
                    "dateTime": start_dt.isoformat(),
                    "timeZone": TIMEZONE
                },
                "end": {
                    "dateTime": end_dt.isoformat(),
                    "timeZone": TIMEZONE
                },
                # Reminder 60 minutes before for prep
                "reminders": {
                    "useDefault": False,
                    "overrides": [
                        {"method": "popup", "minutes": 60},
                        {"method": "email",  "minutes": 60}
                    ]
                }
            }

            created_event = service.events().insert(
                calendarId=calendar_id,
                body=event
            ).execute()

            created.append({
                "student":  student_name,
                "time":     time_key,
                "link":     created_event.get("htmlLink", "")
            })

        return created

    except Exception as e:
        print(f"Calendar event creation error: {e}")
        return []