# memory.py
# All Mem0 memory operations live here
# Keeps memory logic separate from agent logic and UI logic
# Two functions only:
# - save_session_summary() — called when student clicks End Session
# - get_student_memory()   — called in future steps to fetch past memory

from mem0 import MemoryClient
import streamlit as st
import os
from dotenv import load_dotenv

load_dotenv()
# ── Mem0 client ────────────────────────────────────────────────────────────
def get_mem0_client():
    api_key = os.getenv("MEM0_API_KEY") 
    return MemoryClient(api_key=api_key)

# ── Save session summary to Mem0 ───────────────────────────────────────────
# Called after End Session button is clicked
# messages = full chat history list of dicts {"role":..., "content":...}
# student_id = used as user_id in Mem0 so memories are per student
# summary = plain text summary generated by AI from the conversation
def save_session_summary(student_id: str, summary: str):
    try:
        client = get_mem0_client()

        # Mem0 stores memory mapped to a user_id
        # We use student_id as user_id so each student has their own memory
        # messages format Mem0 expects: list of role/content dicts
        client.add(
            messages=[
                {
                    "role": "user",
                    "content": summary
                }
            ],
            user_id=student_id,
            # metadata helps identify what type of memory this is
            # useful later when we have multiple memory types
            metadata={"type": "session_summary"}
        )
        return True
    except Exception as e:
        print(f"Mem0 save error: {e}")
        return False

# ── Fetch student memory from Mem0 ─────────────────────────────────────────
# Used in M5 to give AI context about past sessions
# Keeping this here now so it is ready when we need it
# ── Fetch student memory from Mem0 ─────────────────────────────────────────
# Used in M5 to give AI context about past sessions
# Keeping this here now so it is ready when we need it
def get_student_memory(student_id: str) -> str:
    try:
        client = get_mem0_client()

        memories = client.search(
            query="student session history",
            filters={"user_id": student_id},
            limit=10
        )

        if not memories:
            return "No previous session history found for this student."

        # Some Mem0 versions return {"results": [...]}
        if isinstance(memories, dict):
            memories = memories.get("results", [])

        memory_text = "\n".join([
            f"- {m['memory']}"
            for m in memories
            if isinstance(m, dict) and "memory" in m
        ])

        if not memory_text:
            return "No previous session history found for this student."

        return f"PAST SESSION MEMORY:\n{memory_text}"

    except Exception as e:
        return f"Could not fetch memory: {e}"